spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html

server:
  port: 8081

logging.level:
  org.hibernate:
    SQL: debug
    type: trace